services:
  db:
    image: postgres:16-alpine
    container_name: artesa-db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-artesa_db}
    ports:
      - "3001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - artesa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  app:
    build: .
    container_name: artesa-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --experimental-vm-modules
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-artesa_db}
      JWT_SECRET: ${JWT_SECRET:-artesa_secret_key}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600}
      PORT: ${PORT:-3000}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - artesa-network
    restart: unless-stopped

networks:
  artesa-network:
    name: artesa-network

volumes:
  postgres-data:
    name: artesa-postgres-data
