GET http://localhost:3000/dashboard/task-calendar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0NDQzNjEwOSwiZXhwIjoxNzQ0NDM5NzA5fQ.p7GDt05-6xliiFR4LVN-nwoWuGPov4OUqzvuE5YZkTw

### GET Active Talent Pie Chart
GET http://localhost:3000/dashboard/active-talent-pie-chart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0NDQ0MTk3NSwiZXhwIjoxNzQ0NDQ1NTc1fQ.bURhVDKqKWiubxnwYsXOdxbaXICLlSV1E88qN12Tk90

### GET Income Chart
GET http://localhost:3000/dashboard/income-chart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0NDQ1MjQ5MywiZXhwIjoxNzQ0NDU2MDkzfQ.gNrudpagMB3mfq7yEAFej2u9HdfeLv9b2pCa-BPcxS0

### GET Deliverable Chart
GET http://localhost:3000/dashboard/deliverable-chart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0NDQ2NDE4MiwiZXhwIjoxNzQ0NDY3NzgyfQ.D-a9Rld68-2EVBLYx_44PbjzlThh4K_AaxlBZZmsrh4