### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "rizkim0072@gmail.com",
    "password" : "pw1234"
}

### GET Read Project Detail
GET http://localhost:3000/projects/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyaXpraW0wMDcyQGdtYWlsLmNvbSIsImVtYWlsIjoicml6a2ltMDA3MkBnbWFpbC5jb20iLCJyb2xlIjoiRlJFRUxBTkNFUiIsImlhdCI6MTc0MTMzODE5NSwiZXhwIjoxNzQxMzQxNzk1fQ.YiiJeOvDyhTIbRz--HbvaCf7_rz25IKt-0ZsuZ8QeOw


### POST Create Project
POST http://localhost:3000/projects/create-project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaXJla3NpQGdtYWlsLmNvbSIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0MTMzMTM4OCwiZXhwIjoxNzQxMzM0OTg4fQ.7s2Te2KWI0cJle4CTD5gSWSPDSQ9EJjUqyUckfT3e2Y

{
    "name": "Artsi",
    "description": "Project Management Software development project.",
    "startDate": "2024-10-21",
    "finishedDate": "2024-11-21",
    "fee": 10000000,
    "mou": "https://docs.google.com/document/d/1HGoqGKWcSipQPCo_wE-eqAp2qcjXMHl1/edit?tab=t.0",
    "clientId": 9
}

### UPDATE PROJECT
PUT http://localhost:3000/projects/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaXJla3NpQGdtYWlsLmNvbSIsImVtYWlsIjoiZGlyZWtzaUBnbWFpbC5jb20iLCJyb2xlIjoiRElSRUtTSSIsImlhdCI6MTc0MTMzNDUwMywiZXhwIjoxNzQxMzM4MTAzfQ.EiMetgPYLw6w4jJ7hUFAKaSbgZU_Fo0zHh2MnNu7V_I

{
    "id": 9,
    "name": "ARTSI",
    "description": "Project Management Software development project.",
    "startDate": "2024-10-21",
    "finishedDate": "2024-11-21",
    "fee": 10000000,
    "mou": "https://docs.google.com/document/d/1HGoqGKWcSipQPCo_wE-eqAp2qcjXMHl1/edit?tab=t.0",
    "clientId": 8
}
