export enum NotificationType {
    NEW_ASSIGNMENT = 'NEW_ASSIGNMENT', // For Talent/SMS
    COMMISSION_TRANSFERRED = 'COMMISSION_TRANSFERRED', // For Talent
    NEW_PROJECT_FOR_GM = 'NEW_PROJECT_FOR_GM', // For GM
    NEW_PROJECT_FOR_CLIENT = 'NEW_PROJECT_FOR_CLIENT', // For Client
    NEW_CONTENT_FOR_TALENT = 'NEW_CONTENT_FOR_TALENT', // For Talent
    NEW_SUBMISSION_FOR_SMS = 'NEW_SUBMISSION_FOR_SMS', // For SMS
    CONTENT_DEADLINE_REMINDER = 'CONTENT_DEADLINE_REMINDER', // For Talent (via Cron)
    CONTENT_VERIFIED_FOR_CLIENT = 'CONTENT_VERIFIED_FOR_CLIENT',
    TALENT_ASSIGNED_TO_PROJECT = "TALENT_ASSIGNED_TO_PROJECT", // For Client
}

export enum RelatedEntityType {
    PROJECT = 'PROJECT',
    CONTENT = 'CONTENT',
    SUBMISSION = 'SUBMISSION',
    COMMISSION = 'COMMISSION',
    USER = 'USER',
}
